### ISSUE TITLE
fsoc solution validate appears broken

### ISSUE THREAD

**Issue by ekquasar** [cisco-open/fsoc#84]
Yay new FSOC update came out; I downloaded and built it.
```
> fsoc solution validate

   ⨯ The folder /Users/.../xyz is not a solution package root folder
   ⨯ No solution manifest found in "/Users/.../xyz"; please run this command in a folder with a solution or use the --solution-bundle flag
```
ok I will try the `--solution-bundle` flag:
```
> fsoc solution validate --solution-bundle=xyz.zip
Flag --solution-bundle has been deprecated, it is no longer available.
   ⨯ The --solution-bundle flag is no longer available; please use direct validate instead.
```
Ouch.

Version:
```
> git rev-parse --short HEAD

3d77968
```

**Comment by ekquasar** [comment]
The real solution is that I have to do `cd /path/to/solution && cd xyz` i.e. I run `fsoc solution validate` from a new location now.

That's not what's documented.

**Comment by pnickolov** [comment]
Hi @ekquasar, judging from the commit hash, you are using an unreleased version of fsoc (HEAD of main) rather than the latest released version. It contains some changes to the `solution` commands that are still being revised (see PR #85) and will most likely change before they get released. Can you use the released version?
That said, I tried the latest HEAD and it seems to work as expected; there is no change from its prior behavior (except for removing the `--solution-bundle` flag). Here is what it looks like, using a test solution called `peternic-test` (which I have in a subdirectory under my fsoc work dir but could have been anywhere):

```
~/prj/oss-fsoc/peternic-test$ ../fsoc solution validate
Creating peternic-test.zip archive...
✓ Platform API call (POST /solnmgmt/v1beta/solutions)
Solution peternic-test version 1.0.18 and tag stable was successfully validated.
```

The expectation is that you run fsoc with the solution root directory (where the manifest resides) as current working directory.

**Comment by ekquasar** [comment]
The behavior changed from being able to run in the parent directory of the solution bundle to requiring that fsoc be run in the solution bundle root dir (where manifest.json lives).

Closing because this isn't a bug, it appears to be intended.
